# snip shell completion — fish
# Add to ~/.config/fish/config.fish:
#   source (snip completion fish | psub)

# Disable file completions by default
complete -c snip -f

# Subcommands
complete -c snip -n "__fish_use_subcommand" -a "add" -d "Add a new snippet"
complete -c snip -n "__fish_use_subcommand" -a "list" -d "List snippets"
complete -c snip -n "__fish_use_subcommand" -a "search" -d "Fuzzy search snippets"
complete -c snip -n "__fish_use_subcommand" -a "show" -d "Show snippet content"
complete -c snip -n "__fish_use_subcommand" -a "run" -d "Run a snippet"
complete -c snip -n "__fish_use_subcommand" -a "edit" -d "Edit snippet in editor"
complete -c snip -n "__fish_use_subcommand" -a "update" -d "Update snippet metadata"
complete -c snip -n "__fish_use_subcommand" -a "rm" -d "Remove a snippet"
complete -c snip -n "__fish_use_subcommand" -a "delete" -d "Remove a snippet"
complete -c snip -n "__fish_use_subcommand" -a "export" -d "Export snippets"
complete -c snip -n "__fish_use_subcommand" -a "import" -d "Import snippets"
complete -c snip -n "__fish_use_subcommand" -a "sync" -d "Sync with GitHub Gists"
complete -c snip -n "__fish_use_subcommand" -a "ui" -d "Interactive TUI"
complete -c snip -n "__fish_use_subcommand" -a "config" -d "View/modify config"
complete -c snip -n "__fish_use_subcommand" -a "exec" -d "Execute snippet immediately"
complete -c snip -n "__fish_use_subcommand" -a "pipe" -d "Pipeline mode (stdin→template→stdout)"
complete -c snip -n "__fish_use_subcommand" -a "alias" -d "Generate shell aliases"
complete -c snip -n "__fish_use_subcommand" -a "doctor" -d "Health check"
complete -c snip -n "__fish_use_subcommand" -a "stats" -d "Library statistics"
complete -c snip -n "__fish_use_subcommand" -a "recent" -d "Recently used snippets"
complete -c snip -n "__fish_use_subcommand" -a "last" -d "Re-run last executed snippet"
complete -c snip -n "__fish_use_subcommand" -a "init" -d "Guided setup"
complete -c snip -n "__fish_use_subcommand" -a "grab" -d "Import from URL or GitHub"
complete -c snip -n "__fish_use_subcommand" -a "import-history" -d "Suggest commands from shell history"
complete -c snip -n "__fish_use_subcommand" -a "history" -d "Show snippet version history"
complete -c snip -n "__fish_use_subcommand" -a "diff" -d "Diff two versions of a snippet"
complete -c snip -n "__fish_use_subcommand" -a "undo" -d "Rollback to previous version"
complete -c snip -n "__fish_use_subcommand" -a "team" -d "Team workspace management"
complete -c snip -n "__fish_use_subcommand" -a "suggest" -d "Context-aware snippet suggestions"
complete -c snip -n "__fish_use_subcommand" -a "seed" -d "Seed example snippets"
complete -c snip -n "__fish_use_subcommand" -a "mcp" -d "Start MCP server for AI agent integration"
complete -c snip -n "__fish_use_subcommand" -a "help" -d "Show grouped help"
complete -c snip -n "__fish_use_subcommand" -a "share" -d "Publish snippet(s) as public Gist"
complete -c snip -n "__fish_use_subcommand" -a "unshare" -d "Delete a shared Gist"
complete -c snip -n "__fish_use_subcommand" -a "unpublish" -d "Delete a shared Gist (alias)"
complete -c snip -n "__fish_use_subcommand" -a "discover" -d "Search public gists shared by the community"
complete -c snip -n "__fish_use_subcommand" -a "watch" -d "Watch a snippet for changes and re-run on save"
complete -c snip -n "__fish_use_subcommand" -a "watch-history" -d "Watch shell history for repeated commands"

# Options per subcommand
complete -c snip -n "__fish_seen_subcommand_from add" -l lang -d "Language"
complete -c snip -n "__fish_seen_subcommand_from add" -l tags -d "Comma-separated tags"
complete -c snip -n "__fish_seen_subcommand_from list" -s t -l tag -d "Filter by tag"
complete -c snip -n "__fish_seen_subcommand_from list" -l lang -d "Filter by language"
complete -c snip -n "__fish_seen_subcommand_from list" -l sort -d "Sort order" -a "name usage recent"
complete -c snip -n "__fish_seen_subcommand_from run" -l dry-run -d "Print without executing"
complete -c snip -n "__fish_seen_subcommand_from run" -l confirm -d "Skip confirmation"
complete -c snip -n "__fish_seen_subcommand_from show" -l edit -d "Open in editor"
complete -c snip -n "__fish_seen_subcommand_from show" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from show" -l raw -d "Raw content output"
complete -c snip -n "__fish_seen_subcommand_from show" -l rev -d "Show specific version"
complete -c snip -n "__fish_seen_subcommand_from stats" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from stats" -l streak -d "Show usage streak"
complete -c snip -n "__fish_seen_subcommand_from import-history" -l last -d "Analyze last N history lines"
complete -c snip -n "__fish_seen_subcommand_from import-history" -l min-count -d "Minimum run count"
complete -c snip -n "__fish_seen_subcommand_from import-history" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from update" -l tags -d "Comma-separated tags"
complete -c snip -n "__fish_seen_subcommand_from update" -l lang -d "Language"
complete -c snip -n "__fish_seen_subcommand_from sync" -a "push pull"
complete -c snip -n "__fish_seen_subcommand_from config" -a "set get"
complete -c snip -n "__fish_seen_subcommand_from history" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from history" -l limit -d "Max versions to show"
complete -c snip -n "__fish_seen_subcommand_from diff" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from undo" -l rev -d "Rollback to specific version"
complete -c snip -n "__fish_seen_subcommand_from undo" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from team" -l lang -d "Language for snip team add"
complete -c snip -n "__fish_seen_subcommand_from team" -l tags -d "Comma-separated tags"
complete -c snip -n "__fish_seen_subcommand_from team" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from team" -a "init add list sync push status" -d "Team subcommands"
complete -c snip -n "__fish_seen_subcommand_from share" -l copy -d "Copy Gist URL to clipboard"
complete -c snip -n "__fish_seen_subcommand_from share" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from unshare" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from unpublish" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from discover" -l lang -d "Filter by language"
complete -c snip -n "__fish_seen_subcommand_from discover" -l limit -d "Max results"
complete -c snip -n "__fish_seen_subcommand_from discover" -l recent -d "Browse recent public gists"
complete -c snip -n "__fish_seen_subcommand_from discover" -l snip-only -d "Only snip-shared gists (with --recent)"
complete -c snip -n "__fish_seen_subcommand_from discover" -l json -d "JSON output"
complete -c snip -n "__fish_seen_subcommand_from watch" -l editor -d "Editor to open (e.g. vim, code)"
complete -c snip -n "__fish_seen_subcommand_from watch-history" -l interval -d "Poll interval in seconds"
complete -c snip -n "__fish_seen_subcommand_from watch-history" -l last -d "Recent history lines to analyze"
complete -c snip -n "__fish_seen_subcommand_from watch-history" -l min-count -d "Minimum run count to suggest"
complete -c snip -n "__fish_seen_subcommand_from watch-history" -l auto -d "Auto-save without prompting"
complete -c snip -n "__fish_seen_subcommand_from watch-history" -l once -d "Run once and exit"
