/**
 * snip alias — generate shell aliases for all snippets.
 *
 * Usage:
 *   eval "$(snip alias)"          # bash/zsh
 *   snip alias fish | source      # fish
 *
 * Every snippet becomes a shell command:
 *   deploy-api → snip exec deploy-api
 */

const storage = require('../storage');

function aliasCmd(shell) {
    const s = (shell || '').toLowerCase().trim();
    const detected = s || (process.env.SHELL || '').toLowerCase();
    const isFish = detected.includes('fish');

    const snippets = storage.listSnippets();
    if (!snippets.length) {
        console.error('No snippets. Add one with: snip add <name>');
        process.exitCode = 1;
        return;
    }

    const lines = [];

    if (isFish) {
        lines.push('# snip aliases — generated by `snip alias fish`');
        for (const snip of snippets) {
            const safe = snip.name.replace(/[^a-zA-Z0-9_-]/g, '_');
            lines.push(`function ${safe}; snip exec ${snip.name} $argv; end`);
        }
    } else {
        lines.push('# snip aliases — generated by `snip alias`');
        for (const snip of snippets) {
            const safe = snip.name.replace(/[^a-zA-Z0-9_-]/g, '_');
            lines.push(`alias ${safe}='snip exec ${snip.name}'`);
        }
    }

    console.log(lines.join('\n'));
}

module.exports = aliasCmd;
